version: "3.9"

services:
  todo-db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=todolist
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  todo-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: base
    container_name: todo-backend
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./src:/workspace/src
    expose:
      - '5000'
    links:
      - todo-db
    environment:
      - POSTGRES_DB=todolist
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=todo-db
    command: "node ./build/src/server"

  todo-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-frontend
    ports:
      - "3000:3000"
    stdin_open: true
    links:
      - todo-backend
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
